# Generated by Django 3.1 on 2020-03-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('hello', '0001_initial'), ('hello', '0002_question_choice1')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('choice1', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
